### ISSUE TITLE
Crashing when importing import QtQuick.Controls 1.x

### ISSUE THREAD

**Issue by Noahdw** [qmlnet/qmlnet#103]
I believe the issue I'm having is related to this https://bugreports.qt.io/browse/QTBUG-64697, which causes my program to crash when importing  QtQuick.Controls 1.x using Intel onboard 620 Graphics. Their proposed solution was to use `QCoreApplication::setAttribute(Qt::AA_DisableShaderDiskCache)` but this doesn't seem to be achievable with Qml.Net. Any ideas how I can accomplish the equivalent of this?

**Comment by MaxMommersteeg** [comment]
Does it crash when running https://github.com/qmlnet/qmlnet-examples? What OS are you on, maybe I can reproduce the crash.

**Comment by Noahdw** [comment]
I'm running on windows 10. It works with QtQuick.Controls 2.x. To be honest I never really looked at what the difference between QtQuick.Controls 1 and 2 was, but now that I look I see that I can accomplish when I need with 2.x. Guess this is kinda a non-issue now, thanks though.
