### ISSUE TITLE
Qt virtual keyboard - QML module

### ISSUE THREAD

**Issue by ed10vi** [qmlnet/qmlnet#107]
Would it be possible to include this module?

**Comment by pauldotknopf** [comment]
Have you tried it? I'm pretty sure I included it in the bundled native libs.

**Comment by ed10vi** [comment]
I did.
This is the output:
`QQmlApplicationEngine failed to load component
file:///home/edv/Dev/qtq-tst/Main.qml:3 module "QtQuick.VirtualKeyboard" is not installed`

And this is the content in native/qml
`~/.nuget/packages/qml.net.linuxbinaries/0.7.0/runtimes/linux-x64/native/qml$ ls
builtins.qmltypes  QtCanvas3D          QtMultimedia   QtQuick          QtSensors     QtWebSockets
Qt                 QtGamepad           QtNfc          QtQuick.2        QtTest        QtWebView
Qt3D               QtGraphicalEffects  QtPositioning  QtRemoteObjects  QtWayland
QtBluetooth        QtLocation          QtQml          QtScxml          QtWebChannel`

**Comment by pauldotknopf** [comment]
Ah, I see. I will make sure it is in the next release.

For now, you can build the native libs yourself against your own Qt installation (with VirtualKeyboard installed).

**Comment by ed10vi** [comment]
OK, thank you

**Comment by pauldotknopf** [comment]
The virtual keyboard is now present as of ```0.8.0```.

**Comment by ed10vi** [comment]
I get this error now

```
QQmlApplicationEngine failed to load component
file:///home/ed10vi/dev/qmlnet-vk/Main-vk.qml:15 Type InputPanel unavailable
qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:125 Type Keyboard unavailable
qrc:/QtQuick/VirtualKeyboard/content/components/Keyboard.qml:36 module "QtQuick.VirtualKeyboard.Plugins" is not installed
```
