### ISSUE TITLE
Cursor Changes on Mouse Hover?

### ISSUE THREAD

**Issue by mwegner** [qmlnet/qmlnet#108]
I'm new to QML, so somewhat embarrassingly I'm not sure if this is a broader QML issue or an issue with the wrapper here.  (I have made some small tools with Qt Widgets binding for Go, but that's a completely different ball of wax).

How does one get cursor changes on i.e. button mouse hovers working?  The GIF on the [example project page](https://github.com/qmlnet/qmlnet-examples) doesn't have them, and I haven't been able to make them work on macOS Mojave or Windows.  I tried some explicit MouseArea in the .qml, just to make sure that wasn't it.

Thought I'd ask before I go digging further...

**Comment by pauldotknopf** [comment]
Good question. You are expecting a "pointer finger" when hovering over the buttons?

Regardless, you are correct in guessing that this is just a QML question, not specific to this integration.

**Comment by MaxMommersteeg** [comment]
You mean something like this? https://github.com/MaxMommersteeg/Qml.Net.TodoApp/blob/master/src/TodoApp.FrontEnd/Components/Behaviors/PointingHandCursorOnHover.qml

You should be able to run the app locally.

**Comment by mwegner** [comment]
> You mean something like this? 

Perfect, thanks!  That's exactly what I was looking for.  Tested working in macOS/Windows standalone builds (publish with release target and libraries/binaries brought in).
