### ISSUE TITLE
High Dpi Scaling

### ISSUE THREAD

**Issue by tezine** [qmlnet/qmlnet#111]
Hi, is it possible to enable High DPI Scaling, like QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling); ?

**Comment by MaxMommersteeg** [comment]
Not implemented yet iirc, see: https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/QCoreApplication.cs

**Comment by pauldotknopf** [comment]
Yup, not done yet. Very easy to do. I'll likely squeeze it in next time I do a release.

**Comment by vadi2** [comment]
For anyone else looking:

```csharp
    RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();

    QGuiApplication.SetAttribute(Qml.Net.ApplicationAttribute.EnableHighDpiScaling, true);

    using (var app = new QGuiApplication(args))
    {
```

List of flags can be found [here](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/ApplicationAttribute.cs).
