### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by Ticky-Ticky** [qmlnet/qmlnet#116]
Hello! 
I have a problem with starting Qml.Net app on Linux (CentOs 7, x64). 

App is crashing on start with error: 

> The type initializer for 'Qml.Net.Internal.Interop' threw an exception. ---> System.Exception: Library could not be loaded: libQt5QuickControls2.so.5: cannot open shared object file: No such file or directory: /home/myuser/myapp/libQmlNet.so

Both libQmlNet.so and libQt5QuickControls2.so.5 are exist in folder /home/myuser/myapp/
Can you help me? 
Thanks in advance

**Comment by MaxMommersteeg** [comment]
Could you share a link to your code, so I can reproduce it locally?

**Comment by Ticky-Ticky** [comment]
I have this error with demo example: https://github.com/qmlnet/qmlnet-examples

**Comment by Ticky-Ticky** [comment]
Problem appears when you build a self-contained application with .net core libs included. 
As far as I see there are some troubles with publishing self-contained qml.net application: there are no sub-folders in publish directory, all files and libs lay in one directory without any structure. 

Also I can show log with L_DEBUG=all, if it is needed

**Comment by norwynn** [comment]
Somewhat new with .net core here.  I got the same thing with the sample.  Getting the error below:

![image](https://user-images.githubusercontent.com/20890162/55670089-89277c00-58b2-11e9-8d66-91faffaa48cb.png)

Below is the output.  Which folder should be copied over to linux (ubuntu 14.04 lts)?
![image](https://user-images.githubusercontent.com/20890162/55670037-c0e1f400-58b1-11e9-9571-b9788f16a4a4.png)

I tried both.  Publish with all the files, even the "missing" one in the error above.  Am i missing something about the deployment of files?

**Comment by pauldotknopf** [comment]
Yeah, publishing self-contained apps isn't currently supported, because of how NuGet flattens directories when publishing.

See [this](https://github.com/dotnet/cli/issues/9794) issue.

I have plans to make the Qt environment not deployed as a part of the NuGet packages, and instead, a zip that is downloaded from some network location. The ```libQmlNet.so``` will still be deployed as a part of the NuGet packages though.

**Comment by norwynn** [comment]
Hi,

These are the settings for the publish in VS, its now Framework dependent instead of self-contained.
![image](https://user-images.githubusercontent.com/20890162/55671127-2092cc00-58bf-11e9-9a3f-fcc1d3a6b312.png)

Same as the screenshot from my previous comment above, which folder do I copy over to the target Linux environment?  **Publish** or **linux-x64**.

**Comment by pauldotknopf** [comment]
Now that I think about it, I think it will break in framework dependent mode too.

The solution would be to publish without the ```Qml.Net.*Binaries``` packages, and manually extract the ```Qml.Net.LinuxBinaries``` contents into the directory, preserving the directory structure.

The directory structure is important, and it is what get's destroyed when ```dotnet``` does it's publish.

This is a top priority to fix.

**Comment by pauldotknopf** [comment]
This will be resolved as a part of #87

**Comment by pauldotknopf** [comment]
This has been resolved as of version ```0.8.0```. You can checkout the latest [examples](https://github.com/qmlnet/qmlnet-examples) for verification.

**Comment by Ticky-Ticky** [comment]
After updating to 0.9.0, the first app start takes very long time. The second and further starts are fast, even after reboot. 
Before updating all starts were fast.

**Comment by pauldotknopf** [comment]
> After updating to 0.9.0, the first app start takes very long time (both on Windows and Linux).

Yup. That is the time it takes to auto-download a usable Qt runtime into the users directory. See [this](https://github.com/qmlnet/qmlnet/blob/11e09c0e67998c06415cac81039d7b1bd4818839/src/net/Qml.Net/Runtimes/RuntimeManager.Discovery.cs#L39) for more info.

Documentation hasn't been written yet, but you can get around this by deliverying the Qt runtime with your application. Extract a [*-runtime.tar-gz](https://github.com/qmlnet/qt-runtimes/releases) to where your executable lives. It will get discovered/used.
