### ISSUE TITLE
Warnings when initialize FileDialog

### ISSUE THREAD

**Issue by Chukak** [qmlnet/qmlnet#117]
For example, my code in `Main.qml`
```
Components.FilesDialog
{
    id: filesDialog
}
```
And `FilesDialog.qml`
```
FileDialog 
{
    id: filesDialog
    // ...
}
```

When i launch the app, i get two warnings
```
.../.nuget/packages/qml.net.linuxbinaries/0.7.0/runtimes/linux-x64/native/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
.../.nuget/packages/qml.net.linuxbinaries/0.7.0/runtimes/linux-x64/native/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
```
Version of qmlnet: `0.7.0`

**Comment by MaxMommersteeg** [comment]
I was able to reproduce the warnings on my Windows machine. Qml's `FileDialog` component uses the `QQControlsFileDialog` section of the application-specific `QSettings`. AFAIK we currently don't support configuring these settings.

More: https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html#details

**Comment by Chukak** [comment]
Ok, now i know what reproduces these warnings.
Thanks for your reply!

**Comment by MaxMommersteeg** [comment]
Not sure if we should close this issue just yet. I think we need to support this. What do you think @pauldotknopf ?

**Comment by pauldotknopf** [comment]
Yeah, this needs to be done IMO.

**Comment by Diviis** [comment]
I have the same issue, on Windows with MSVC 2019 compiler (32 and 64 bits). 

Application ouput : 
`file:///F:/QtOnline/5.15.2/msvc2019/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///F:/QtOnline/5.15.2/msvc2019/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")`

main.qml : 
`import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Dialogs 1.2

ApplicationWindow {
    width: 1280
    height: 720
    visible: true


    FileDialog {

        title: "Please choose a file"
        folder: shortcuts.home
        onAccepted: {
            console.log("You chose: " + fileDialog.fileUrls)

        }
        onRejected: {
            console.log("Canceled")

        }
        Component.onCompleted: visible = true
    }
}
`
