### ISSUE TITLE
Couldn't find the native Qml.Net library.

### ISSUE THREAD

**Issue by MaxMommersteeg** [qmlnet/qmlnet#120]
I updated my apps using Qml.Net to the latest package versions (0.9.0):
- https://github.com/MaxMommersteeg/Qml.Net.TodoApp
- https://github.com/MaxMommersteeg/Qml.Net.Chat

Both wouldn't work on version 0.8.0 and 0.9.0 since I did not specify following line before using Qml.Net:
```csharp
RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();
```

Exception:

> System.TypeInitializationException: 'The type initializer for 'Qml.Net.Internal.Interop' threw an exception.'

Inner Exception:

> Exception: Couldn't find the native Qml.Net library.

Would be a nice add to the wiki pages imho.

**Comment by pauldotknopf** [comment]
Yeah, that isn't a good experience.

Maybe we should write to stdout a warning that a suitable runtime couldn't be found.

**Comment by MaxMommersteeg** [comment]
That defenitely help the developer.

Is it required to call that method or are there other ways that it could work without?

**Comment by pauldotknopf** [comment]
It has to be called. Automatically downloading tars for the web inside of a static initializer is a bad idea IMO.

Also, some people using Qml.Net may want to use the runtime properly located in /usr/lib.

**Comment by SwiTool** [comment]
Yea indeed, calling `RuntimeManager.DiscoverOrDownloadSuitableQtRuntime()` solved my issue.
I followed [this](https://qmlnet.github.io/setup/managed-hosting/) but no clue of that method here.

Thanks
