### ISSUE TITLE
How to create .ui files with Qt Creator?

### ISSUE THREAD

**Issue by vadi2** [qmlnet/qmlnet#124]
![Selection_424](https://user-images.githubusercontent.com/110988/56461393-35239980-6380-11e9-8d39-bfc6ab4e4f2b.png)

Qt Creator doesn't like custom modules - what's the right way to deal with this in Qml.Net?

**Comment by pauldotknopf** [comment]
Ignore the intellisense errors for now. Everything is valid. It's just the IDE getting confused.

This will be fixed in #72. Follow that issue if you want to be notified when this is completed.

**Comment by vadi2** [comment]
Thanks! I'll follow that issue. Unfortunately the graphical d'n'd design bails out on the errors, but it is fairly simple to comment things back and forth.

**Comment by vadi2** [comment]
For anyone else looking: all you need to do is comment/uncomment your `import` statement for Qt Creator to work fine. Adding the following two tasks into `tasks.json` and calling them in your `launch.json` would work:

```json
        {
            "label": "disable-qml",
            "command": "sed",
            "type": "shell",
            "args": [
                "-i",
                "'s|import test 1.1|// import test 1.1|g'",
                "${workspaceFolder}/Main.qml"
            ],
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$tsc"
        },
        {
            "label": "enable-qml",
            "command": "sed",
            "type": "shell",
            "args": [
                "-i",
                "'s|// import test 1.1|import test 1.1|g'",
                "${workspaceFolder}/Main.qml"
            ],
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$tsc"
        }
```
