### ISSUE TITLE
Support Blazor/WebAssembly

### ISSUE THREAD

**Issue by logicethos** [qmlnet/qmlnet#127]
It would be amazing to be able to build GUI apps for the browser.

**Comment by vadi2** [comment]
It's also a business case thing - Electron is a really good choice for businesses as you can share (some) of the investment for online and offline.

**Comment by shayneoneill** [comment]
Qt controls would be terrible to use on HTML. They don't behave like HTML at all. Further, Qt is a native technology. Your just not going to get this to work unless you lobby google to make Chrome able to access Native libraries which I 100% guarantee they'll refuse.

**Comment by pauldotknopf** [comment]
Closing this, as this isn't likely something we'd support.
