### ISSUE TITLE
How to access QML object in .NET?

### ISSUE THREAD

**Issue by vadi2** [qmlnet/qmlnet#129]
I'd like to change the label of a Groupbox in QML using .NET - what is the right way to do this? I see that https://github.com/qmlnet/qmlnet/pull/122 has went in recently but not sure if it's related / how to use it.

**Comment by pauldotknopf** [comment]
The issue you referenced is unrelated.

You'd want to do something like this:

```qml
NetType {
    id: netType
}
GroupBox {
    title: netType.groupBoxTitle
}
```

```c#
public class NetType
{
    private string _groupBoxTitle;

    [NotifySignal]
    public string GroupBoxTitle
    {
        get => _groupBoxTitle;
        set
        {
            if (_groupBoxTitle == value)
            {
                return;
            }
            _groupBoxTitle = value;
            this.ActivateProperty(x => x.GroupBoxTitle);
        }
    }
}
```

**Comment by vadi2** [comment]
Thanks, that works! And... simple question, how can I work with this class from within .NET? I need an object to reference. I looked at the qml-examples but could not find a solution.

**Comment by vadi2** [comment]
I see from the docs that `RegisterType()` instantiates it, so I guess I need some way to get a reference to that.

**Comment by vadi2** [comment]
Got it sorted! Using it from the same class seems to be fine.
