### ISSUE TITLE
Support QQmlComponent and QuickView for interacting with QML Objects from C#

### ISSUE THREAD

**Issue by iWeaverMan** [qmlnet/qmlnet#131]
https://doc.qt.io/qt-5/qtqml-cppintegration-interactqmlfromcpp.html

**Comment by pauldotknopf** [comment]
I haven't actually tested a QmlComponent, but my understanding it that it is passed around as a QObject.

We support interacting with QObjects, by using the INetQObject type.

Try declaring a method with INetQObject as a parameter, and pass a QML component to it. I'd imagine that it would work.

**Comment by pauldotknopf** [comment]
With this:

```qml
Item {
   property int testprop: 4
}
```

I was able to interact with it via:

```csharp
public class NetClass
{
    public void Method(INetQObject value)
    {
    }
}
```

Feel free to re-open if you have a repro.
