### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by ShalokShalom** [qmlnet/qmlnet#132]
Hi there :) 

Since I think that F# is fully C# compatible and due to the fact that this implementation works via types, is it likely that F# is fully supported. 

It would be nice to have some examples since this is surely interesting for a lot of devs.

**Comment by MaxMommersteeg** [comment]
It will probably be compatible since C# and F# compile to the same intermediate language. F# isn't familiar ground for me, but you could elaborate on the docs with a pull request if you like.

**Comment by ShalokShalom** [comment]
I am currently not in the community involved anymore, while F# is a superset of C#, so it is probably very simple to transfer the implementation. Tons of thanks!
