### ISSUE TITLE
Is it possible to use Qt Creator QML debugging?

### ISSUE THREAD

**Issue by vadi2** [qmlnet/qmlnet#134]
See https://doc.qt.io/qtcreator/creator-debugging-qml.html

**Comment by pauldotknopf** [comment]
Yes, it is possible, but only if you use [unmanaged hosting](https://qmlnet.github.io/setup/unmanaged-hosting/).

**Comment by vadi2** [comment]
If I use unmanaged hosting, can I still do C# debugging?

**Comment by pauldotknopf** [comment]
Yup.

Using the IDE of your choice, you "attach to process" after you launch the app from Qt Creator.

**Comment by vadi2** [comment]
Aha, thanks. I've got https://github.com/health-validator/Hammer out now - one of the first few C# and QML 'real' apps? At least open-source ones in GitHub. I'll look into unmanaged hosting then.

**Comment by pauldotknopf** [comment]
Interesting.

What field are you in? What is the drive for that project?

**Comment by vadi2** [comment]
Come in to Gitter, happy to explain!
