### ISSUE TITLE
Update "Quick Overview" Section

### ISSUE THREAD

**Issue by nolav** [qmlnet/qmlnet#136]
https://github.com/qmlnet/qmlnet#quick-overview

The quick overview example does not work. I am new to using Qml and Qml.Net and I spent a lot of time trying to figure out why the example would throw an exception at:

`using (var engine = new QQmlApplicationEngine())`

It is because the example provided on the front project page is missing the line:

`RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();`

before creating the QQmlApplicationEngine.

I know there is an example repository that is linked from the main page but it is typical for projects to have a quick (hello world style) working example on the front page and then link to examples demonstrating more complex features. I figured if I cant get the most simple example to run then more complex examples would not help me. I think updating the example or removing it and only linking the examples repo would save others a lot of time.

**Comment by vadi2** [comment]
I agree. Want to throw in a PR?
