### ISSUE TITLE
how to install QT manually

### ISSUE THREAD

**Issue by zzstuzor** [qmlnet/qmlnet#143]
Hello, I downloaded your example project and tried to run it but it hangs in the method RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();

I have a very bad internet connection. Where can I download the minimal SDK or runtime for QT ? Everything I find online is 1GB+..

Thanks

**Comment by MaxMommersteeg** [comment]
Not sure what the minimum required runtime is, but downloading the runtime with the RuntimeManager is only required once.

**Comment by zzstuzor** [comment]
Yes but unfortunately after trying 10+ times it just never works. Internet
is very unreliable in the Indian Ocean islands :-(

Is it possible to manually download and install? The method doesnt seem the
most resilient at downloading..

**Comment by MaxMommersteeg** [comment]
You could do this all manually by having a look at following class:
`https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.cs`

This is essentially what lives under `RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();`.

That code is responsible for selecting the correct runtime and downloading it from https://github.com/qmlnet/qt-runtimes and putting it in your specific user directory.

I assume that downloading from https://github.com/qmlnet/qt-runtimes will be more practical in your case.

**Comment by zzstuzor** [comment]
Thanks Max, appreciate the help. Will try and report back with my progress.

**Comment by vadi2** [comment]
If you can, post instructions on how to do that, since for any real deployment the runtime would need to be deployed with the application - due to the issues you mention. I haven't quite figured out where things should go just yet, but having a tool to download the runtimes knowing the location to put them into would help for CI builds.

**Comment by pauldotknopf** [comment]
These are the packages you will need to extract.

https://github.com/qmlnet/qt-runtimes/releases

I will document this as soon as I can. I am currently in the hospital.

**Comment by vadi2** [comment]
Oh no! Sorry to hear that. Hope you recover fast (with a small bill).

**Comment by zzstuzor** [comment]
> https://github.com/qmlnet/qt-runtimes/releases
> I will document this as soon as I can.

Where do I put these files once I have downloaded them? Presumably somewhere like user\.nuget\ ?

**Comment by zzstuzor** [comment]
> Where do I put these files once I have downloaded them? Presumably somewhere like user.nuget\ ?

c:\Users\**<USER>**\.qmlnet-qt-runtimes\qt-5.12.2-ad0689c-win-x64\qt\
