### ISSUE TITLE
QByteArray support

### ISSUE THREAD

**Issue by geigertom** [qmlnet/qmlnet#148]
I'm trying to pass a QByteArray containing raw image data to my registered .net object by attaching to the emitted signal of a QVideoFilter that I wrote in c++.

```
QByteArray byteArray = byteArrayFromImage(img);
emit m_filter->finished(byteArray);
```

The connection works, and I can pass objects, e.g. QString to the signal listener:

```
var handler = qVideoFilter.AttachSignal("finished", parameters => {
    Console.WriteLine("onFinished: " + parameters );
});
```

But apparently QByteArray is not (yet) supported:

`Unsupported variant type: QVariant::QByteArray QByteArray`

I tried converting it to a QVariantList beforehand, which actually works, but the conversion on each frame takes far to much time to be usable in real time image processing.

Is it possible to pass QByteArray or a simple byte array to .net? What would be the aproach to extend qml.net to support types like QByteArray? I would love to help implement this feature but I need a little push in the right direction.

Thanks,
Tom

**Comment by pauldotknopf** [comment]
This is interesting.

I'd say just pass a pointer to the raw byte array, but QByteArray is ref counted, and it may be deleted from underneath you. You'd definately want to maintain an instance of QByteArray to copy the contents to a .net array at a later time.

Adding this support would be easy.

I'd say update [```NetVariant```](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Internal/Qml/NetVariant.cs) to support a new ```NetVariantType``` of ```QByteArray```. Then you'd have ```NetVariant.SetBytes(byte[]) and ```byte[] NetVariant.GetBytes()```.

However, this means that you'll never be able to modify ```QByteArray``` from .NET, since you'd only be sending receiving raw .NET byte arrays.

If you need the instance of ```QByteArray``` in .NET so that you could maybe pass the raw pointer somewhere else, or modify it directly, you could implement something like [```INetJsValue```](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net.Tests/Qml/JsValueTests.cs), but call it ```INetQByteArray```. That would have methods for you to modify the internal instance of ```QByteArray```.

What approach would be best for you? We could support both.

**Comment by geigertom** [comment]
For my use case I don't need an instance of the `QByteArray` in .NET, a raw .NET byte array would be just fine. I will take a look at `NetVariant` and see what I can do to extend it the way you suggested.

**Comment by geigertom** [comment]
So i tried to implement support for QByteArray, but can't get past this error on application startup:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception. ---> System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'return value': Invalid managed/unmanaged type combination.   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at Qml.Net.Internal.Interop.LoadDelegates(Object o, IntPtr library, IPlatformLoader loader) in /home/tom/workspace/qmlnet/fromgit/qmlnet/src/net/Qml.Net/Internal/Interop.cs:line 146
   at Qml.Net.Internal.Interop.LoadInteropType[T](IntPtr library, IPlatformLoader loader) in /home/tom/workspace/qmlnet/fromgit/qmlnet/src/net/Qml.Net/Internal/Interop.cs:line 136
   at Qml.Net.Internal.Interop..cctor() in /home/tom/workspace/qmlnet/fromgit/qmlnet/src/net/Qml.Net/Internal/Interop.cs:line 64
   --- End of inner exception stack trace ---
   at Qml.Net.Internal.Interop.get_QCoreApplication() in /home/tom/workspace/qmlnet/fromgit/qmlnet/src/net/Qml.Net/Internal/Interop.cs:line 98
   at Qml.Net.Host.Run(String[] args, Func`5 action) in /home/tom/workspace/qmlnet/fromgit/qmlnet/src/net/Qml.Net/Host.cs:line 60
   at NetHost.Program.Main(String[] _) in /home/tom/workspace/qmlnet/fromgit/qmlnet/samples/hosting/net/Program.cs:line 42
```

I'm wondering which types I should use on the c++ and .NET side respectively. I thought that `std::vector<unsigned char>` might be a good representation for a byte array because from what I understand, we needed to know the array's size beforehand if we just use `unsigned char*`. (My c++ knowledge is very limited).

So given` typedef std::vector<unsigned char> LPARRAY;` my NetVariant.cpp looks like this:

```
Q_DECL_EXPORT LPARRAY net_variant_getBytes(NetVariantContainer* container) {
    return container->variant->getBytes();
}

Q_DECL_EXPORT void net_variant_setBytes(NetVariantContainer* container, LPARRAY values) {
    container->variant->setBytes(values);
}
```

In NetVariant.cs I have:

```
public byte[] ByteArray
{
    get => Interop.NetVariant.GetBytes(Handle);
    set => Interop.NetVariant.SetBytes(Handle, value);
}

....

[NativeSymbol(Entrypoint = "net_variant_setBytes")]
public SetBytesDel SetBytes { get; set; }

[SuppressUnmanagedCodeSecurity]
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void SetBytesDel(IntPtr variant, byte[] value);

[NativeSymbol(Entrypoint = "net_variant_getBytes")]
public GetBytesDel GetBytes { get; set; }

[SuppressUnmanagedCodeSecurity]
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate byte[] GetBytesDel(IntPtr variant);
```

This leads to the error above. If instead of `sdt::vector<unsigned char>` I use `unsigned char*` I cannot even build the project due to the following error:

```
/home/tom/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h:121: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system
 #  define Q_STATIC_ASSERT_X(Condition, Message) static_assert(bool(Condition), Message)
```

Any hints on how to get this working?

**Comment by pauldotknopf** [comment]
You'd have to marshal that yourself, it isn't blittable. The best bet would be to make ```net_variant_getBytes``` take in a c-style callback that passes in raw pointer and the number of bytes, for you to then marshal in .NET.

**Comment by pauldotknopf** [comment]
```
net_variant_getBytes(variant, (pointer, count) { /*.NET code to convert IntPtr to byte array*/ })
```

**Comment by geigertom** [comment]
Thanks, I realize that I need to read more on the concept of marshalling to gain a better understanding.

**Comment by geigertom** [comment]
I finally got it working:

```
Q_DECL_EXPORT LPARRAY net_variant_getBytes(NetVariantContainer* container, int &count) {
    const QByteArray byteArray = container->variant->getBytes();
    count = byteArray.count();;
    return byteArray.constData();
}
```

```
public byte[] ByteArray
{
    get {
        int count;
        IntPtr arrayHandle = Interop.NetVariant.GetBytes(Handle, out count);
        byte[] managedArray = new byte[count];
        Marshal.Copy(arrayHandle, managedArray, 0, count);
        return managedArray;
    }
}
```

I will create a PR in the next few days as soon I find the time.
