### ISSUE TITLE
QML.NET for mobile

### ISSUE THREAD

**Issue by zzstuzor** [qmlnet/qmlnet#156]
Does anyone know if it's possible to build QML.NET apps for mobile? Has anyone tried it? Any thoughts, pitfalls, suggestions, recommendations?

We're considering build an app with QML.NET and it'd be great if we could just build one app for desktop and mobile with layouts that automatically adjust...

**Comment by zzstuzor** [comment]
> Does anyone know if it's possible to build QML.NET apps for mobile? Has anyone tried it? Any thoughts, pitfalls, suggestions, recommendations?
> 
> We're considering build an app with QML.NET and it'd be great if we could just build one app for desktop and mobile with layouts that automatically adjust...

**Comment by pauldotknopf** [comment]
I have not done it myself, but I don't see anything preventing it.

I'm open to supporting it as a community contribution, but I won't be able to set aside any time to test/support it.

**Comment by zzstuzor** [comment]
ok I might look into it and report back with my findings

**Comment by rathwell** [comment]
Just curious, are these comments still relevant?  Where you stated that Android/iOS is more work than can be justified?

https://github.com/qmlnet/qmlnet/issues/53

**Comment by pauldotknopf** [comment]
Sorry, let me be clear. I won't be spending any time getting iOS/Android working, apart from answering any questions you may have.

If someone wished to support it, I'd except any merge requests needed to make it happen. But iOS/Android will always be supported by someone other than me. I'm simply don't have the bandwidth.

Furthermore, IMO, Qt for mobile apps isn't a good fit. There are many outstanding issues that they haven't been addressing. It isn't a first-class supported platform by the Qt team.

It would be fun to see if someone can get QmlNet running on Android/iOS though.

**Comment by rathwell** [comment]
Thanks, that's what I was looking for..a rough idea of the size of work that would be involved. I think it would be fun too, but I really only have random hours here and there.

**Comment by MosiQt** [comment]
Apart from Qt, I'm wondering how possible it is to use dotnet core for android? I thought Xamarin is for that purpose, and the technology is somewhat different that dotnet core. Also, I couldn't find any working examples or piece of codes for android.

**Comment by pauldotknopf** [comment]
Android/iOS work use Mono, so Qml.Net would have to have some minor changes.

**Comment by xsacha** [comment]
Is there a reason you can't have Android and iOS use dotnet core?
You can certainly compile dotnet core for Android.
Qt works well on Android and iOS with little effort. I already have cross-platform apps that work on Android/iOS/Linux/Mac/windows (using only c++/qml).

**Comment by zzstuzor** [comment]
My understanding is that it is possible - you'd have to compile the qml.net
binaries for Android and iOS separately, which involves a bunch of work
wiring it all up, and probs more I'm not aware of.

I believe Paul has stated he doesn't have time to do it himself, nor
support it, but said he's happy to add it as a community contribution if
someone else wants to do it.

**Comment by pauldotknopf** [comment]
I'm closing this issue, considering this isn't likely something we'd be doing. Thanks!
