### ISSUE TITLE
Using with F#

### ISSUE THREAD

**Issue by dangerousHobo** [qmlnet/qmlnet#163]
I've taken a shot at using qmlnet within an F# project:

```
open System
open Qml.Net
open Qml.Net.Runtimes

[<EntryPoint>]
let main argv =
    RuntimeManager.DiscoverOrDownloadSuitableQtRuntime() |> ignore

    let app = new QGuiApplication(argv)
    let engine = new QQmlApplicationEngine()
    engine.Load("Main.qml")
    app.Exec()
```

Running this I get the following:

```
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
```

Anything obvious that I'm missing? I have both Qml.Net and Qml.Net.WindowsBinaries packages added to my project.

**Comment by MaxMommersteeg** [comment]
See issue: https://github.com/qmlnet/qmlnet/issues/65

**Comment by dangerousHobo** [comment]
Thanks, I should have waited longer, the error shows after 40sec and the app window pops up after 80sec. I assumed it was dead after the error.

**Comment by MaxMommersteeg** [comment]
No problem. The first launch was probably slow since it was downloading the runtime. Second launch should be significantely faster.
