### ISSUE TITLE
Cannot use already existing installation of QT 5.10.1

### ISSUE THREAD

**Issue by bairog** [qmlnet/qmlnet#171]
Hello.

On thet [Requirements](https://qmlnet.github.io/introduction/requirements/) page we can see **Qt 5.10+**. So I've expected to be able to use QML .NET with already existing installation of QT.

I'm on Windows 10 1903 x64. I've installed QT 5.10.1 prebuilt components for **MSVC 2017 64-bit** via [qt-opensource-windows-x86-5.10.1.exe](https://download.qt.io/archive/qt/5.10/5.10.1/qt-opensource-windows-x86-5.10.1.exe). 
Resulting installation folder is **C:\Qt\Qt_5.10.1\5.10.1\msvc2017_64** (during installation process I was able to choose only **C:\Qt\Qt_5.10.1** folder - all subfolders are selected automatically). 
And of course that resulting folder contains all necessary subfolders - **bin**, **plugins** and **qml**.

I'm trying to run QML .Net example using my existing installation:
`RuntimeManager.ConfigureRuntimeDirectory(@"C:\Qt\Qt_5.10.1\5.10.1\")`

But that results in error that 

> Plugins directory didn't exist "CC:\Qt\Qt_5.10.1\5.10.1\qt\plugins"

Looks like **qt** subfolder name is hardcoded inside [RuntimeManager.Configure.cs](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.Configure.cs)

So how to deal with that situation? 
How to properly use QML .NET with already existing installation of QT 5.10.1 (editing RuntimeManager.Configure.cs and recompile QML.Net.dll is not a good option)?

Thank you.

**Comment by pauldotknopf** [comment]
Hmm, it looks like that ```RuntimeManager.Configure``` needs to poke around a bit more.

The only thing that method does though is set some environment variables. You could set those yourself in ```Program.Main```. Really though, in production environments, this is how it should be done, considering most published applications embed the Qt framework privately in their own folder.

**Comment by pauldotknopf** [comment]
Also, if you use your own Qt runtime, make sure you compile the native bits for Qml.Net yourself and put them in your PATH somewhere.

**Comment by pauldotknopf** [comment]
Allow me to clarify.

All Qt libs (when using private headers) must be compiled against the exact Qt version they are running against. So, you can't just use "Qml.Net.WindowsBinaries" with any Qt runtime. If you use your own Qt installation, you must only use the Qml.Net package, and compile the native libs that are in "Qml.Net.WindowsBinaries" yourself.

The build/installation is really simple. See [here](https://github.com/qmlnet/qmlnet/blob/develop/src/native/build.bat).

The "Qml.Net" package will find an invoke the native C-interop QmlNet.dll properly.

**Comment by bairog** [comment]
What I've tried (on Windows 10 1903 x64):

0. Installed QT 5.10.1 prebuilt components for **MSVC 2017 64-bit** via [qt-opensource-windows-x86-5.10.1.exe](https://download.qt.io/archive/qt/5.10/5.10.1/qt-opensource-windows-x86-5.10.1.exe). Resulting installation folder is **C:\Qt\Qt_5.10.1\5.10.1\msvc2017_64**.
1. Downloaded [qmlnet](https://github.com/qmlnet/qmlnet) repository. Inside [build.bat](https://github.com/qmlnet/qmlnet/blob/develop/src/native/build.bat) i've changed qmake to **C:\Qt\Qt_5.10.1\5.10.1\msvc2017\bin\qmake** and jom to **C:\Qt\Qt_5.10.1\5.10.1\msvc2017\Tools\QtCreator\bin\jom**.
2. Started **Visual Studio 2019 Developer Command Prompt v16.3.6** and started build.bat inside it. Succesfully built **\output\QmlNet.dll**.
3. Downloaded [qmlnet-examples](https://github.com/qmlnet/qmlnet-examples) repository. Removed Nuget references to all runtimes (MacOSX, Linux and Windows). Copied **QmlNet.dll** to project folder. 
4. Added [RuntimeManager.Configure.cs](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.Configure.cs) to **qmlnet-examples** project (inside it I've changed namespace to **Features** and changed hardcoded **qt** subdirectory name to **msvc2017_64**). Changed `RuntimeManager.DiscoverOrDownloadSuitableQtRuntimes();` to `RuntimeManager.ConfigureRuntimeDirectory(@"C:\Qt\Qt_5.10.1\5.10.1\");`.
5. Compiled **qmlnet-examples** project (restored all needed Nuget packages of course) and started debugging.
6. `RuntimeManager.ConfigureRuntimeDirectory(@"C:\Qt\Qt_5.10.1\5.10.1\");` finished correctly. But `QQuickStyle.SetStyle("Material");` results in exception:

> The type initializer for 'Qml.Net.Internal.Interop' (inside Qml.Net) threw an exception: Symbol loading failed. Symol name: type_info_setPrefVariantType (inside NetNativeLibLoader)

So what I am doing wrong?

**Comment by bairog** [comment]
I've tried the same approach with **Qt 5.11.0** on **Debian 9**. On Step **2** I've succesfully compiled **libQmlNet.so** via **build.sh**. But again on Step **6** I've faced the same exceptions.
Looks like I'm going the wrong way :)

**Comment by pauldotknopf** [comment]
Make sure you compile the native lib using the same exact version as the NuGet library. Checkout the write tag in the git repo.

**Comment by bairog** [comment]
Oh, that waas my mistake. I used latest version of native lib instead of **release 0.10.1**. Now it's working (both Windows and Linux).

Final instruction for using Qml .Net with existing QT installation (tested on **Windows 10 1903 x64** with **QT 5.10.1** and **Debian 9** with **QT 5.11.0**):
What I've tried (on Windows 10 1903 x64):

1. Download [qmlnet](https://github.com/qmlnet/qmlnet/releases) repository for **the same exact version as the NuGet library**. 
2. On Windows: Inside [build.bat](https://github.com/qmlnet/qmlnet/blob/develop/src/native/build.bat) change qmake to **Your_QT_bin_path\qmake** and jom to **Your_QtCreator_bin_path\jom**. Start **Visual Studio 2019 Developer Command Prompt v16.3.6 x64** and run build.bat inside it.
2*. On Linux: Simply run build.sh.
3.  On both systems Native C-interop library wil be built to **\output\QmlNet.dll**. Copy that library to your project folder.
4. Use code from [RuntimeManager.Configure.cs](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.Configure.cs) directly in your project. Make sure that inside `RuntimeManager.ConfigureRuntimeDirectory()` you've changed hardcoded **qt** subdirectory name to **msvc2017_64** or the one that you use.
5. Use R`untimeManager.ConfigureRuntimeDirectory(Your_QT_directory)` instead of `RuntimeManager.DiscoverOrDownloadSuitableQtRuntimes();`
6. Now your code doesn't need to download Qml .Net runtimes and can run on existing QT installation.

**Comment by bairog** [comment]
Oh, that waas my mistake. I used latest version of native lib instead of **release 0.10.1**. Now it's working (both Windows and Linux).

Final instruction for using Qml .Net with existing QT installation (tested on **Windows 10 1903 x64** with **QT 5.10.1** and **Debian 9** with **QT 5.11.0**):
What I've tried (on Windows 10 1903 x64):

1. Download [qmlnet](https://github.com/qmlnet/qmlnet/releases) repository for **the same exact version as the NuGet library**. 
2. On Windows: Inside [build.bat](https://github.com/qmlnet/qmlnet/blob/develop/src/native/build.bat) change qmake to **Your_QT_bin_path\qmake** and jom to **Your_QtCreator_bin_path\jom**. Start **Visual Studio 2019 Developer Command Prompt v16.3.6 x64** and run build.bat inside it.
2*. On Linux: Simply run build.sh.
3.  On both systems Native C-interop library wil be built to **\output\QmlNet.dll**. Copy that library to your project folder.
4. Use code from [RuntimeManager.Configure.cs](https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.Configure.cs) directly in your project. Make sure that inside `RuntimeManager.ConfigureRuntimeDirectory()` you've changed hardcoded **qt** subdirectory name to **msvc2017_64** or the one that you use.
5. Use R`untimeManager.ConfigureRuntimeDirectory(Your_QT_directory)` instead of `RuntimeManager.DiscoverOrDownloadSuitableQtRuntimes();`
6. Now your code doesn't need to download Qml .Net runtimes and can run on existing QT installation.
