### ISSUE TITLE
Image element cannot display web image

### ISSUE THREAD

**Issue by MingHuiLiu** [qmlnet/qmlnet#174]
Image element cannot display web image.
This bug can now be resolved by converting to a local image, but I want to use webview and find that it is not currently supported.  I just want to play the video (playing a web video requires a custom cookie header), I don't know if there is a good solution at the moment.

**Comment by pauldotknopf** [comment]
WebView is supported, it just isn't provided by the pre-compiled Qt runtime (because it's super large).

For more advanced scenarios, I'd recommend: https://qmlnet.github.io/setup/unmanaged-hosting/

**Comment by pauldotknopf** [comment]
Closing, as the ```Image``` element is a Qt component, not of this project.

**Comment by MingHuiLiu** [comment]
MouseArea does not work🤔

**Comment by pauldotknopf** [comment]
Post your QML? It's likely just a markup issue.

**Comment by MingHuiLiu** [comment]
import QtQuick 2.11
import QtQuick.Controls 2.4
import QtQuick.Layouts 1.3
import QtGraphicalEffects 1.0
import QtQuick.Window 2.3
import Features 1.0

import QtMultimedia 5.0
import QtWebView 1.0



ApplicationWindow {
    id: window
    width: 800
    height: 600
    visible: true
    title: "Qml.Net"


            Rectangle{
                border.color: "#ff0000"
                height:500
                width:500

                DropArea{
                    
                height:500
                width:500
            anchors.fill: parent;

            onDropped: {

                if(drop.hasUrls){

                    for(var i = 0; i < drop.urls.length; i++){

                        console.log(drop.urls.length);

                        console.log(drop.urls[i]);

                    }

                }

    }
}
            }

**Comment by vadi2** [comment]
Have a look at https://github.com/qmlnet/qmlnet/issues/142, might be similar!
