### ISSUE TITLE
Can't set icon to the window

### ISSUE THREAD

**Issue by ujjaldas89** [qmlnet/qmlnet#181]
There is no setWindowIcon method available from .Net

**Comment by ujjaldas89** [comment]
Is there a way to fix this?

**Comment by pauldotknopf** [comment]
It would have to be exposed, which should be straigt-forward.

**Comment by devmil** [comment]
Should be fixed now @pauldotknopf ?

**Comment by pauldotknopf** [comment]
Yup.
