### ISSUE TITLE
Does this still stand?

### ISSUE THREAD

**Issue by jor1196** [qmlnet/qmlnet#182]
Hi, I see that this project hasn't updated your src in a while
still standing or is leaving?

**Comment by pauldotknopf** [comment]
Still standing. The problem is, I implemented for a project for work, and it is currently stable/released and doesn't need any more changes as of now. If I find time, I may update or make changes, but things are quite at the moment.

**Comment by shaxxx** [comment]
@pauldotknopf Thanks for the great project. Please, when possible provide basic "Getting started" documentation. This shouldn't include any info about compiling Qt, just what Qt versions are supported, what Qt components should be downloaded and installed, needed system wide changes, etc.. I believe this would dramatically lower the entry barrier and involve even more people and help the project grow.

Thank you.
