### ISSUE TITLE
FileDialog.open() does not work from Qml.Net

### ISSUE THREAD

**Issue by ujjaldas89** [qmlnet/qmlnet#183]
Has FileDialog component has been handled. When I execute filedialog.open in the qml file .net shows as unrecognized command.

**Comment by pauldotknopf** [comment]
I'm sorry for the delay here. Can you provide more info? What do you mean by "unrecognized command"?

**Comment by ujjaldas89** [comment]
I figured out a way how to make it work. I am sorry for the delayed response.

**Comment by vadi2** [comment]
How did you make it work?

**Comment by ujjaldas89** [comment]
If paul allows. Then I can actually upload my project. This will also add another example project into the repository.

**Comment by pauldotknopf** [comment]
Upload it here, and I'll see if anything should be added to our examples.

**Comment by ujjaldas89** [comment]
[Example Project.zip](https://github.com/qmlnet/qmlnet/files/5080664/Example.Project.zip)
@pauldotknopf 
I have attached the complete project.
@vadi2 
`    FileDialog {
        id: fileDialog
        selectMultiple: true
        selectExisting: true
        title: "Choose .tcf file(s)..."
        **visible: true**
        nameFilters: [ "Tcf files (*.tcf)" ]
        onAccepted: fileDialogAccepted(fileDialog.fileUrl, fileDialog.fileUrls)
    }
    Component.onCompleted: {          
        console.log("Load completed")
        **fileDialog.visible = false**
    }`

@vadi2 : The problem was if Visible is not set to true the FileDialog.Open won't work. But if Visible is set to true the FileDialog pops up after the Component load is complete. So, after some trial and error, I figured out that is the Visible is set to false on the Component load everything goes back to normal.

I regret the delay in response.
