### ISSUE TITLE
 error : Value cannot be null. (Parameter 'folderName')

### ISSUE THREAD

**Issue by adrielbenvindo** [qmlnet/qmlnet#186]
build error in Build.csproj

**Comment by pauldotknopf** [comment]
Did you run ```git submodule update --init```?

**Comment by adrielbenvindo** [comment]
Thanks, it's resolved. now the problem is version of dotnet core, the version that I'm using is 3.1.2

**Comment by pauldotknopf** [comment]
Yeah, should be a simple moniker change. It should work just fine when you update them.
