### ISSUE TITLE
Not Support for running on ARM

### ISSUE THREAD

**Issue by zhangjingru** [qmlnet/qmlnet#187]
dotnet publish -r linux-arm

dotnet Features.dll
Unhandled exception. System.Exception: Unsupported target
   at Qml.Net.Runtimes.RuntimeManager.RuntimeTargetToString(RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindQtRuntime(String[] runtimeDirectories, String qtVersion, RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Features.Program.Main(String[] args) in D:\Project\qmlnet-examples\src\Features\Program.cs:line 12

source code:
        private static string RuntimeTargetToString(RuntimeTarget target)
        {
            switch (target)
            {
                case RuntimeTarget.Windows64:
                    return "win-x64";
                case RuntimeTarget.LinuxX64:
                    return "linux-x64";
                case RuntimeTarget.OSX64:
                    return "osx-x64";
                case RuntimeTarget.Unsupported:
                    throw new Exception("Unsupported target");
                default:
                    throw new Exception($"Unknown target {target}");
            }
        }

**Comment by elgonzo** [comment]
Try building and running your project as a 64-bit program, if your ARM platform supports this.

It seems Qml.Net only supports 64 bit. (See the source code of the `GetCurrentRuntimeTarget()` method right below the source code of the `RuntimeTargetToString(RuntimeTarget target)` method. It specifically tests for pointer width being 64 bits (8 bytes), and will return `RuntimeTarget.Unsupported` if that is not the case.)

**Comment by shartte** [comment]
Which platform is Qt on for this? Linux/X11 or Android?

**Comment by pauldotknopf** [comment]
Anything other than ```win-x64```, ```linux-x64```, ```osx-x64```, you'll need to compile/package the native bits to QmlNet yourself.

Compile ```./src/native/QmlNet/QmlNet.pro``` and make sure it's available in your ```PATH```/```LD_LIBRARY_PATH```.
