### ISSUE TITLE
Did not understand how to run app

### ISSUE THREAD

**Issue by EarsKilla** [qmlnet/qmlnet#191]
Project was created with `dotnet new console`, included all required packages from readme (including windows, mac, linux libs)

`RuntimeManager.DiscoverOrDownloadSuitableQtRuntime()` throwing following exception:  
```
An unhandled exception of type 'System.DllNotFoundException' occurred in NetNativeLibLoader.dll: 'Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory'
```

Trying to run on `Linux Mint 19.3 Tricia` using `net core 3.1`

Getting same exception with [qmlnet-examples](https://github.com/qmlnet/qmlnet-examples)

---

[run logs with LD_DEBUG=all.txt](https://github.com/qmlnet/qmlnet/files/4493559/run.logs.with.LD_DEBUG.all.txt)
If my project is required for some reasons: [testqt.zip](https://github.com/qmlnet/qmlnet/files/4493574/testqt.zip)

**Comment by r9guy** [comment]
same here.
 I fought it should be straightforward, add nuget, build and all runs.

**Comment by pauldotknopf** [comment]
Sorry for the delay.

I'm not really sure what is causing your issue.

It seems that .NET can't find ```libdl.so```, which should be present in your distribution.

Is it possible there is a mixup between ```/lib``` and ```/lib64```? Maybe symlink the two and try again?

**Comment by EarsKilla** [comment]
Solved!  

Seems that my system don't contains `libdl.so` which is included in `libc6-dev` package (found in google [here](https://askubuntu.com/questions/987740/how-to-install-dl#comment1591148_987740))

After installation `libc6-dev` package and it's dependencies i was able to start app.

Please, include in readme note about `libc6-dev` for linux

**Comment by vadi2** [comment]
Could you send in a PR for that?

**Comment by EarsKilla** [comment]
@vadi2 done #193

**Comment by r9guy** [comment]
what about windows? I have same Exception on windows.

**Comment by vadi2** [comment]
Are you certain it's the same?

**Comment by r9guy** [comment]
this is the full exception.
nuget package version 0.10.1
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Qml.Net.Internal.Interop' threw an exception.
  Source=Qml.Net
  StackTrace:
   at Qml.Net.Internal.Interop.get_NetVariantList()
   at Qml.Net.Internal.Qml.NetVariantList..ctor()
   at Qml.Net.QCoreApplication.Create(Int32 type, List`1 args, Int32 flags)
   at Qml.Net.QCoreApplication..ctor(Int32 type, String[] args, Int32 flags)
   at Qml.Net.QGuiApplication..ctor(String[] args, Int32 flags)
   at QMLTest.Program.Main(String[] args) in C:\Users\Arsham\source\repos\QMLTest\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Unable to find the native Qml.Net library. Try calling "RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();" in Program.Main()

**Comment by vadi2** [comment]
See it's different. Are you doing what it's telling you to do?

**Comment by r9guy** [comment]
Dear Vadim.
my apologies. after closer look I have seen that the exception is indeed different and my intention to post was based on the title of issue itself. 
anyway regarding what I do. I just created a console .netcore application, added nuget QML.NET and QML.NET Windows binaries. 
just exactly as is described in [here](https://qmlnet.github.io/setup/managed-hosting/)
my program is exactly as is given in managed hosting setup page.
I don't know what could be wrong from my end.
project is zipped and attached
[QMLTest.zip](https://github.com/qmlnet/qmlnet/files/4512090/QMLTest.zip)

**Comment by r9guy** [comment]
found that my code was different from @EarsKilla 's that it is missing `RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();`

added that . now there's no exception, it not documented on website but on issue #143  .

**Comment by EarsKilla** [comment]
@r9guy 
> it is not documented on website

it's documented in [readme](https://github.com/qmlnet/qmlnet#quick-overview) below `Define a .NET type (POCO)`

**Comment by r9guy** [comment]
@EarsKilla @vadi2 thanks. that helped
