### ISSUE TITLE
Use qml files and images from a resx

### ISSUE THREAD

**Issue by ezruneko** [qmlnet/qmlnet#192]
Is it possible to add and consume images and  qml from a resource file?

**Comment by pauldotknopf** [comment]
Not currently, see #15.

**Comment by ezruneko** [comment]
Oh ok. I didn't see these isssue. Thank you.

It's very important to us that the final user can't modify the GUI or the logic with a simple notepad. 

Is it possible to load qml from a string? To load from a URL or embed, read manually and pass this stream or string to the engine?

**Comment by ezruneko** [comment]
Ok. I

**Comment by ezruneko** [comment]
Ok. Thank you. Our focus is protect qml file from any modifications (to avoid changes in the app logic with a simple notepad). 

It's posible to pass a string to the engine with the qml content? This is solve our issue too.

**Comment by vadi2** [comment]
Are you sure that is a real problem you have?

**Comment by ezruneko** [comment]
Yes it's a real problem. We pass in my corporation a strong security audit. For example we can't use plain config files and can't expose code like scripts or any code not compiled.

**Comment by pauldotknopf** [comment]
I'd recommend using native (unmanaged) hosting. There really aren't any limits when you approach Qml.Net that way.

https://qmlnet.github.io/setup/unmanaged-hosting/
