### ISSUE TITLE
Can't build latest QmlNet with Qt 5.14.2 on Windows

### ISSUE THREAD

**Issue by BrianAllred** [qmlnet/qmlnet#197]
Repo is [here](https://gitlab.com/BrianAllred/qml-yodel).

PATH is set to `C:\Qt\5.14.2\mingw73_64\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%`

Build script:

```
git submodule sync --recursive
git submodule update --init --recursive

mkdir .\bin\release
cd .\bin\release

dotnet restore ..\..\net\
dotnet build -c Release -o .\ ..\..\net\
qmake ..\..\QmlYodel.pro CONFIG+=release DESTDIR=%cd%
mingw32-make
```

![image](https://user-images.githubusercontent.com/5847511/80651628-d76a6880-8a3b-11ea-8ebb-79106a42d338.png)

**Comment by pauldotknopf** [comment]
I'm sorry for the delay here. When I find time to get my Windows box up and running, I'll check it out.

However, it looks to be a simple ```#define``` mix-up and the latest Qt bits. Maybe you could take a stab at it?

**Comment by BrianAllred** [comment]
I downgraded to Qt 5.12.2 using MSVC++ 2017 and still get the same issue. Tried it with a brand new VM and project just to verify it wasn't an environment issue.

I'll take a look when I have time, but my C++ is pretty rusty.

**Comment by BrianAllred** [comment]
After a little bit of investigation, the attached diff fixed the build. I haven't had time to see if it actually runs correctly yet. I'll update when I do.

```
diff --git a/src/native/QmlNet/Hosting/CoreHost.cpp b/src/native/QmlNet/Hosting/CoreHost.cpp
index d3029ce..882a023 100644
--- a/src/native/QmlNet/Hosting/CoreHost.cpp
+++ b/src/native/QmlNet/Hosting/CoreHost.cpp
@@ -22,8 +22,18 @@ static QString nativeModule;
 
 static void* getExportedFunction(const char* symbolName) {
 #ifdef _WIN32
+#ifdef UNICODE
+    wchar_t *array = new wchar_t[nativeModule.length() + 1];
+    nativeModule.toWCharArray(array);
+    array[nativeModule.length()] = 0;
+
+    HMODULE library = GetModuleHandle(nativeModule.isNull() || nativeModule.isEmpty() ? nullptr
+                                                                                      : array);
+#else
     HMODULE library = GetModuleHandle(nativeModule.isNull() || nativeModule.isEmpty() ? nullptr
-                                                                                     : nativeModule.toLocal8Bit());
+                                                                                      : nativeModule.toLocal8Bit());
+#endif
+
     FARPROC symbol = GetProcAddress(library, symbolName);
     return (void*)symbol;
 #else

```

**Comment by BrianAllred** [comment]
Nope. With the above patch, Qt complains at runtime about not being able to find registered .NET types.

**Comment by shartte** [comment]
The root cause here seems to be compiling with _UNICODE defined, which I'd say is usually recommended.
You could try without it though.
