### ISSUE TITLE
How to access elements of List<string> or string[] returned from C# function in QML JS

### ISSUE THREAD

**Issue by FieryRider** [qmlnet/qmlnet#205]
Basically I have function in C# that returns `string[]`. I've registered the class as a type in QML and I can call the function from JS in QML. But I don't know how to loop through the values of the returned `string[]` in JS.
When I `console.log()` the returned value I get `qml: String[](0x555d44926470)`

**Comment by pauldotknopf** [comment]
Use ```Net.toListModel(yourValue)``` to work with it.

Or, ```Net.toVariantList(yourValue)```.

**Comment by pauldotknopf** [comment]
You can also use ```Net.listForEach(yourValue, function(val) {})``` to enumerate it.

**Comment by FieryRider** [comment]
`Net.toListModel(yourValue)` and `Net.listForEach(yourValue, (val) => {})` worked for a C# `List<>`. `Net.toVariantList(yourValue)` gave error `TypeError: Property 'toVariantList' of object JsNetObject(0x5600f4c52f90) is not a function`. I guess it's something that is not in the `0.10.1` release.
For an array none of these worked, giving me `Parameter is not a type that be enumerated.` so I had to use standard `for` loop `for (let i = 0; i < arr.length; i++) { console.log(arr.get(i)) }`
Thanks.
