### ISSUE TITLE
Thread-safe

### ISSUE THREAD

**Issue by FilipoGuci** [qmlnet/qmlnet#210]
Hello, I am a beginner C # developer. I am interested in your qml.net library, please tell me if it’s not difficult for you. Since I cannot use Dispatcher, how can I handle the event safely? Thanks in advance.

**Comment by pauldotknopf** [comment]
Which event are you speaking of, specifically?

**Comment by AndreyVoytsik** [comment]
For example, I have a library that sends, receives and decodes data, I create an event for decoding and subscribe to it in the main form, if you do not use the dispatcher, the form hangs

**Comment by pauldotknopf** [comment]
I don't really know what you are asking. Can you provide a simple ```Program.Main``` with some explanation?

**Comment by AndreyVoytsik** [comment]
lib.dll
public event EventHandler<GetStateEventArgs> OnGetState;
public async Task<GetStateEventArgs> GetState()
{
     //some actions
     OnGetState?.Invoke(this, state);
}
Program.cs
uDP.OnGetState += UDP_OnGetState;
private void UDP_OnGetState(object sender, GetStateEventArgs e)
{
     displayResult = $"Firmware version: {e.Version}"
 }

**Comment by pauldotknopf** [comment]
On the UDP_OnVersion, you must dispatch the data back to the UI thread with ```QCoreApplication.Dispatch```.
