### ISSUE TITLE
Dotnet core 3.1 and DotNet 5 support

### ISSUE THREAD

**Issue by sps014** [qmlnet/qmlnet#212]
I am interested to know what does it takes to add support for Dotnet core 3.1 and DotNet 5 (in future).
This project is amazing , i think whole community would love to see dotnet core 3.1 support.

**Comment by pauldotknopf** [comment]
.NET 3.1 is already supported. We are using it currently at my place-of-work.

I'm not sure about .NET 5, I'm sure it's a similar situation.

**Comment by sps014** [comment]
I tried using with dotnet core 3.1 , i got no errors but no window appeared, i searched and some folk somewhere mentioned it does not support 3.1, hence i asked here , i must be doing something wrong then...
