### ISSUE TITLE
Remove AdvanceDLSupport from project.

### ISSUE THREAD

**Issue by pauldotknopf** [qmlnet/qmlnet#43]
It is great and all, but we aren't using all the features of it. The only thing we get from it is the ability to have a single PInvoke/DllImport for each assembly. We could implement this ourselves by emitting custom classes with os-specific DllImport attributes.

Also, the every project the references ```Qml.Net``` adds multiple files in the root.

![image](https://user-images.githubusercontent.com/523150/43559262-5fdec474-95db-11e8-9c3a-6d08fe3e9741.png)

**Comment by Nihlus** [comment]
I've been on vacation and haven't had time to address the issue with the external annotation files. I'd expect to be able to fix that during next week.

**Comment by Nihlus** [comment]
Found some time - the issue is now fixed.

**Comment by MaxMommersteeg** [comment]
This one is fixed right? https://github.com/qmlnet/qmlnet/commit/6ace3a1bb74b3f06210487795ac779ed8831f6f3

**Comment by Nihlus** [comment]
@MaxMommersteeg At the moment, there's a licensing issue with the new library that Qml.NET uses, since it's copied large portions of code directly from ADL without retaining the LGPL license or the copyright notice.

**Comment by TripleWhy** [comment]
@pauldotknopf This is a serious issue. Right now I would not use qml.net in a commercial application due to [this](https://github.com/Firwood-Software/AdvanceDLSupport/issues/66) and [this](https://github.com/pauldotknopf/net-native-lib-loader/issues/1) licensing uncertainties.

**Comment by DylanFPS** [comment]
Qml.NET needs to stop using the other lib as it’s technically illegal, and I wouldn’t want to be affected by copyright disputes. Plus half of the issue is fixed in ADL now.

I ask that you revert the commit in which the library was replaced. I also advise on adding a PrivateAssets entry on the PackageReference to prevent unneeded redistribution, similar to the one added in ADL with StrictEmit.

**Comment by pauldotknopf** [comment]
I've re-licences NetNativeLibLoader, so there shouldn't be any issues anymore.

And yes, @MaxMommersteeg, this issue is now resolved. Thanks for linting the issues for me.
