### ISSUE TITLE
Sample project doesn't work on Windows

### ISSUE THREAD

**Issue by antonyrey** [qmlnet/qmlnet#70]
Hi,

I tried downloading and launching the sample project "Features", however it doesn't work on my Windows 10 machine with Visual Studio 2017 15.8 : i get an error message for a few seconds and then the program exits.

It is a bit unclear in documentation when does Qt libraries get copied to debug directory.

![image](https://user-images.githubusercontent.com/167333/45805020-f6304700-bcbd-11e8-993d-476f453c4857.png)

Thanks a lot for your help and your great project ;-)

Have a nice day.

Antony

**Comment by antonyrey** [comment]
Thanks for your answer.

I downloaded ZIP of master branch as well, and I have the same Visual Studio version installed.

Do you run it simply by pressing F5 ?

Do I need to install something on my computer ? Visual Studio C++ Redistribuable or something ?

Thanks.

**Comment by pauldotknopf** [comment]
Try this.

Navigate to your ```.nuget/``` package cache and find ```qml.net.windowsbinaries```.

Then, find the Qt libs within that package.

Open them up with this: http://www.dependencywalker.com/

That will tell you if there are any dependencies missing.

Although, I doubt that is the issue.

@antonyrey, Can you send me a private email? I'd like to potentially setup a TeamViewer session to identify what is going wrong with your setup. Email: pauldotknopf at gmail

**Comment by pauldotknopf** [comment]
It turned out to be an issue with the graphics driver.

Qt has some nobs you can turn to fine-tune the graphics/opengl stuff on windows.

See here: http://doc.qt.io/qt-5/windows-requirements.html

In this case, setting ```QT_OPENGL=angle``` resolved the issue for this particular machine/setup.
