### ISSUE TITLE
Add support for QApplication.

### ISSUE THREAD

**Issue by Nihlus** [qmlnet/qmlnet#73]
According to these docs, native look and feel is possible with QML, but only using QApplication and not QGuiApplication. 

http://doc.qt.io/qt-5/qtquickcontrols-overview.html

Is this slated to be added to QML.Net?

**Comment by Nihlus** [comment]
Great!

**Comment by Nihlus** [comment]
Has there been any updates on this?

**Comment by pauldotknopf** [comment]
I've looked at this some more, and I don't think ```QApplication``` should be used with QML applications. It is for supporting ```QWidgets```, which Qml.Net shouldn't be used with.

**Comment by Nihlus** [comment]
It's the official suggested (and only) way of making a Qml application have
reliable native look & feel, which is a very important consideration for
desktop applications.


Is there any specific reason this can't or won't be supported by Qml.Net?
Personally, not having native look & feel and being forced into a mobile
look on desktop is a showstopper.

**Comment by pauldotknopf** [comment]
I've created a sample QML app and my styling doesn't change when switching between ```QApplication``` and ```QGuiApplication```. How exactly does ```QApplication``` effect QML applications?

**Comment by Nihlus** [comment]
As you've already noted, using QApplication by itself does not change the styling. Rather, it enables native look and feel for the modules that support it - namely, QtQuick.Controls 1, and QWidgets. As far as I can read (although I haven't tested it myself) QtQuick.Controls 2 is explicitly intended to *not* provide a platform look and feel, but rather provide a uniform look across platforms.

Thus, the intended use case is QApplication along with QtQuick.Controls 1 to build native look and feel UI applications.

**Comment by pauldotknopf** [comment]
This is implemented in develop.

I will update when it is on NuGet.

**Comment by Nihlus** [comment]
Nice!

**Comment by gridtech-pl** [comment]
@Nihlus were you finally able to gain native look and feel?

**Comment by Nihlus** [comment]
I've been waiting on this issue to be updated with a notification that it's on nuget, so not yet.

**Comment by vadi2** [comment]
I think there's a misunderstanding here. Qt Quick will not give you native desktop widgets.

**Comment by Nihlus** [comment]
QML can use native desktop widgets when using QtQuick.Controls 1 - I use it at work every day in C++.
