### ISSUE TITLE
UI lag when resizing UI

### ISSUE THREAD

**Issue by codec-abc** [qmlnet/qmlnet#77]
Hi,

I wanted to try this out and ran into performance issues when resizing a very basic app.

Disclaimer, I don't know QML/QT, and have little experience with on .Net Core.

Basically, I created a simple .Net Core app with the following single cs file:

```cs
using Qml.Net;
using System;

namespace qmlTest
{
    class Program
    {
        static int Main(string[] args)
        {
            using (var app = new QGuiApplication(args))
            {
                using (var engine = new QQmlApplicationEngine())
                {
                    // TODO: Register your .NET types.
                    // Qml.RegisterType<NetObject>("test");

                    engine.Load(@"Q:\dev2\qml.net\qmlTest\qmlTest\Main.qml");

                    return app.Exec();
                }
            }
        }
    }
}
```

and my `Main.qml` contains the following:

```qml
import QtQuick 2.7
import QtQuick.Controls 2.0
import QtQuick.Layouts 1.0
import QtGraphicalEffects 1.0

ApplicationWindow {
    id: window
    visible: true
    width: 640
    height: 480
    title: qsTr("PhotoFrame")
	Rectangle {
		id: page
		width: 320; height: 480
		color: "lightgray"

		Text {
			id: helloText
			text: "Hello world!"
			y: 30
			anchors.horizontalCenter: page.horizontalCenter
			font.pointSize: 24; font.bold: true
		}
	}
}
```

When resizing the UI lags quite heavily because the window cannot keep the resizing movement. By the way, I am running Windows 10.

**Comment by pauldotknopf** [comment]
You are currently running pure QML, so the problem isn't related to this project.

With that said, there is probably an issue with your Windows install. What graphics card are you using? Are you drivers updated?

Do you run into perf problems running [this](https://github.com/qmlnet/qmlnet-examples) project?

**Comment by pauldotknopf** [comment]
Read this: http://doc.qt.io/qt-5/windows-requirements.html

Try to set ```QT_OPENGL=angle``` before launching the app.

**Comment by codec-abc** [comment]
The sample crash with an Access Violation message. I have a GTX 1070 with version 388.43 for the driver.

**Comment by codec-abc** [comment]
The `QT_OPENGL=angle` solved the lag. However, it is a bit disappointing that a QT (a framework that is a few decade old) does not run well out of the box.

**Comment by pauldotknopf** [comment]
Glad you got it sorted!
