### ISSUE TITLE
Support for Qt Quick Controls 2 Configuration File

### ISSUE THREAD

**Issue by TripleWhy** [qmlnet/qmlnet#86]
How can I use a [Qt Quick Controls 2 Configuration File](http://doc.qt.io/qt-5/qtquickcontrols2-configuration.html)?
There is no support for the qt resource system, but I can use [QT_QUICK_CONTROLS_CONF](http://doc.qt.io/qt-5/qtquickcontrols2-environment.html). It works fine when I specify that as an environment variable for the run configuration in my IDE, but not when I use `System.Environment.SetEnvironmentVariable("QT_QUICK_CONTROLS_CONF", ...);` as the first line of C# code.
What am I missing?

**Comment by pauldotknopf** [comment]
I've noticed that sometimes, environment variables don't work as expected, unless you use Qt's ```qputenv``` method. That method is available in C# using ```Qt.PutEnv(name, value)```.

Try that and tell me if it works. If not, I'll dig in more.

**Comment by TripleWhy** [comment]
That works a lot better, thanks.
