### ISSUE TITLE
Moving Qt binaries into external packages that can be dynamically downloaded?

### ISSUE THREAD

**Issue by pauldotknopf** [qmlnet/qmlnet#87]
Currently, we have these packages:

* ```Qml.Net.WindowBinaries```
* ```Qml.Net.LinuxBinaries```
* ```Qml.Net.OSXBinaries```

Each of these packages contains the entire Qt/QML runtime, as well as a lib required by Qml.Net to interoperate (```libQmlNet.so```). That means each build/release contains the entire Qt/QML runtime, even though the Qt version stays the same.

I'm thinking of updating the above packages to *only* contain the ```libQmlNet.so``` needed for Qml.Net to work. The Qt/QML runtime will be dynamically downloaded and installed either at runtime, or during deployment. I will host the tarballs on GitHub. Each tarball will have a "version.txt" that will declare the Qt version. On startup of the app, if a Qt/QML runtime isn't detected, it will be downloaded.

If you are deploying your app for production, chances are, you don't want users to dynamically download Qt/QML. Instead, you can download the archive yourself, and reference it via a ```QMLNET_QML_RUNTIME_LOCATION``` environment variable.

**Comment by pauldotknopf** [comment]
Another option is to create additional NuGet packages, splitting the Qt/QML runtime and Qml.Net.

* Qml.Net.WindowBinaries
* Qml.Net.WindowBinariesQml
* Qml.Net.LinuxBinaries
* Qml.Net.LinuxBinariesQml
* Qml.Net.OSXBinaries
* Qml.Net.OSXBinariesQml

The ```*BinariesQml``` packages will rarely be updated.

**Comment by devmil** [comment]
Yes! I really like that idea.
I think the second approach fits better in dotnet publish scenarios because it works out of the box and integrates nicely in the underlying Nuget mechanism.

**Comment by pauldotknopf** [comment]
I've created a repo that builds tar files for the Qt runtime for linux-64, win-64 and osx-64. Two tar balls are created for each, one for the runtime (no building/no header files) and another for dev (building).

https://github.com/qmlnet/qt-runtimes/releases/tag/releases

I'm thinking about adding another NuGet package that will help discovery/downloading/installing/configuring Qt runtimes. Something like ```Qml.Net.RuntimeManager```.

The API would look something like this:

```c#
Qml.Net.RuntimeManager.Install(Qml.Net.Versions.RequiredRuntimeVersion);
```

The ```Qml.Net.Versions.RequiredRuntimeVersion``` would be baked into ```Qml.Net```.

Implementors could add this line in their ```Program.Main```, or use ```dotnet qml install``` to install it locally for packaging/distributing.

**Comment by pauldotknopf** [comment]
Solves as of ```0.8.0```.

**Comment by vadi2** [comment]
I'm looking at deploying a Qml.Net app - it looks like `QMLNET_QML_RUNTIME_LOCATION` never made it in. What's the recommended way to deploy the binaries?
