### ISSUE TITLE
Setup Dependabot for automatic NuGet package update PR's.

### ISSUE THREAD

**Issue by MaxMommersteeg** [qmlnet/qmlnet#94]
Keeping NuGet packages up-to-date is a task that is often forgotten. Dependabot is a service that automatically updates NuGet packages by opening up pull requests. This way Qml.Net's packages will always be up-to-date and this will save us some time doing it ourselves.

The service is free for open source projects.

Setup is really easy:
https://dependabot.com/

**Comment by pauldotknopf** [comment]
Done (for Qml.Net.csproj only).
